services:
  dbhub_local:
    image: bytebase/dbhub:latest
    ports:
      - "8933:8080"
    environment:
      - DBHUB_LOG_LEVEL=debug
    command:
      - --transport
      - http
      - --port
      - "8080"
      # Внимание: замените строку ниже на ваши реальные данные для подключения
      - --dsn
      - "postgres://$DB_USER:$DB_PASS@$DB_HOST:5433/marketplace_usercatalog"

